-- ============================================================
-- Supabase Schema  |  Role-Based Facility Reservation
-- and Approval System  |  SAD Lab 4 Section B
-- Run in: Supabase Dashboard > SQL Editor > New query
-- ============================================================

-- ========== TABLE 1: profiles (3 roles) ==========
CREATE TABLE IF NOT EXISTS public.profiles (
  id         UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role       TEXT NOT NULL DEFAULT 'requester'
             CHECK (role IN ('administrator', 'facility_staff', 'requester')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_authed" ON public.profiles;
DROP POLICY IF EXISTS "profiles_insert_own"   ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_own"   ON public.profiles;

CREATE POLICY "profiles_select_authed" ON public.profiles FOR SELECT
  TO authenticated USING (true);
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE
  TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;


-- ========== TABLE 2: facilities ==========
CREATE TABLE IF NOT EXISTS public.facilities (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_name   TEXT NOT NULL,
  facility_type   TEXT NOT NULL,
  capacity        INTEGER NOT NULL DEFAULT 0,
  location        TEXT NOT NULL DEFAULT '',
  description     TEXT DEFAULT '',
  status          TEXT NOT NULL DEFAULT 'Active'
                  CHECK (status IN ('Active', 'Under Maintenance')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_facility_name   ON public.facilities (facility_name);
CREATE INDEX IF NOT EXISTS idx_facility_status ON public.facilities (status);

ALTER TABLE public.facilities ENABLE ROW LEVEL SECURITY;

-- Everyone authenticated can view facilities
DROP POLICY IF EXISTS "facilities_select_authed" ON public.facilities;
CREATE POLICY "facilities_select_authed" ON public.facilities FOR SELECT
  TO authenticated USING (true);

-- Only Administrators can insert/update/delete facilities
DROP POLICY IF EXISTS "facilities_insert_admin" ON public.facilities;
DROP POLICY IF EXISTS "facilities_update_admin_or_staff" ON public.facilities;
DROP POLICY IF EXISTS "facilities_delete_admin" ON public.facilities;

CREATE POLICY "facilities_insert_admin" ON public.facilities FOR INSERT
  TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'administrator'
  ));

-- Admin can do full updates; Staff can update condition/status
CREATE POLICY "facilities_update_admin_or_staff" ON public.facilities FOR UPDATE
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('administrator', 'facility_staff')
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('administrator', 'facility_staff')
  ));

CREATE POLICY "facilities_delete_admin" ON public.facilities FOR DELETE
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'administrator'
  ));


-- ========== TABLE 3: reservations ==========
CREATE TABLE IF NOT EXISTS public.reservations (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_id     BIGINT NOT NULL REFERENCES public.facilities(id) ON DELETE RESTRICT,
  requester_name  TEXT NOT NULL,
  department      TEXT NOT NULL DEFAULT '',
  purpose         TEXT NOT NULL DEFAULT '',
  start_datetime  TIMESTAMPTZ NOT NULL,
  end_datetime    TIMESTAMPTZ NOT NULL,
  status          TEXT NOT NULL DEFAULT 'Pending'
                  CHECK (status IN ('Pending', 'Approved', 'Rejected', 'Scheduled', 'In Use', 'Completed', 'Cancelled')),
  approved_by     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_at     TIMESTAMPTZ,
  user_id         UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT end_after_start CHECK (end_datetime > start_datetime)
);

CREATE INDEX IF NOT EXISTS idx_res_facility  ON public.reservations (facility_id);
CREATE INDEX IF NOT EXISTS idx_res_status    ON public.reservations (status);
CREATE INDEX IF NOT EXISTS idx_res_user      ON public.reservations (user_id);
CREATE INDEX IF NOT EXISTS idx_res_start     ON public.reservations (start_datetime);

ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "res_select_authed" ON public.reservations;
DROP POLICY IF EXISTS "res_insert_authed" ON public.reservations;
DROP POLICY IF EXISTS "res_update_authed" ON public.reservations;
DROP POLICY IF EXISTS "res_delete_authed" ON public.reservations;

CREATE POLICY "res_select_authed" ON public.reservations FOR SELECT
  TO authenticated USING (true);
CREATE POLICY "res_insert_authed" ON public.reservations FOR INSERT
  TO authenticated WITH CHECK (true);
CREATE POLICY "res_update_authed" ON public.reservations FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "res_delete_authed" ON public.reservations FOR DELETE
  TO authenticated USING (true);


-- ========== TABLE 4: audit_logs (BR-B4-10) ==========
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action          TEXT NOT NULL,
  target_table    TEXT NOT NULL,
  target_id       BIGINT,
  details         TEXT DEFAULT '',
  performed_by    UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  performed_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_action ON public.audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_audit_time   ON public.audit_logs (performed_at DESC);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Only admins can see audit logs; everyone can insert (via functions)
DROP POLICY IF EXISTS "audit_select_admin" ON public.audit_logs;
DROP POLICY IF EXISTS "audit_insert_authed" ON public.audit_logs;

CREATE POLICY "audit_select_admin" ON public.audit_logs FOR SELECT
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'administrator'
  ));

CREATE POLICY "audit_insert_authed" ON public.audit_logs FOR INSERT
  TO authenticated WITH CHECK (true);


-- ========== HELPER: log_audit ==========
CREATE OR REPLACE FUNCTION public.log_audit(
  p_action TEXT,
  p_target_table TEXT,
  p_target_id BIGINT,
  p_details TEXT DEFAULT ''
) RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.audit_logs (action, target_table, target_id, details, performed_by)
  VALUES (p_action, p_target_table, p_target_id, p_details, auth.uid());
END;
$$;


-- ========== FUNCTION: submit_reservation ==========
-- BR-B4-01: Only active facilities may be reserved
-- BR-B4-02: Start must precede end (enforced by CHECK constraint)
-- BR-B4-03: Overlapping approved schedules are prohibited
-- BR-B4-08: Facilities under Maintenance cannot be reserved
CREATE OR REPLACE FUNCTION public.submit_reservation(
  p_facility_id BIGINT,
  p_requester_name TEXT,
  p_department TEXT,
  p_purpose TEXT,
  p_start_datetime TIMESTAMPTZ,
  p_end_datetime TIMESTAMPTZ
) RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_id BIGINT; v_status TEXT;
BEGIN
  -- BR-B4-01 / BR-B4-08: Only active facilities
  SELECT status INTO v_status FROM public.facilities WHERE id = p_facility_id;
  IF v_status IS NULL THEN
    RAISE EXCEPTION 'Facility not found.';
  END IF;
  IF v_status = 'Under Maintenance' THEN
    RAISE EXCEPTION 'BR-B4-08: Facility is under maintenance and cannot be reserved.';
  END IF;
  IF v_status <> 'Active' THEN
    RAISE EXCEPTION 'BR-B4-01: Only active facilities may be reserved.';
  END IF;

  -- BR-B4-02: start must precede end
  IF p_start_datetime >= p_end_datetime THEN
    RAISE EXCEPTION 'BR-B4-02: Reservation start must precede end time.';
  END IF;

  -- BR-B4-03: No overlapping approved/scheduled/in-use reservations
  IF EXISTS (
    SELECT 1 FROM public.reservations
    WHERE facility_id = p_facility_id
      AND status IN ('Approved', 'Scheduled', 'In Use')
      AND p_start_datetime < end_datetime
      AND p_end_datetime > start_datetime
  ) THEN
    RAISE EXCEPTION 'BR-B4-03: Overlapping approved schedule detected. Choose a different time.';
  END IF;

  INSERT INTO public.reservations
    (facility_id, requester_name, department, purpose, start_datetime, end_datetime, status, user_id)
  VALUES
    (p_facility_id, p_requester_name, p_department, p_purpose, p_start_datetime, p_end_datetime, 'Pending', auth.uid())
  RETURNING id INTO v_id;

  -- BR-B4-10: Log the submission
  PERFORM public.log_audit('SUBMIT', 'reservations', v_id,
    'Reservation submitted by ' || p_requester_name || ' for facility ' || p_facility_id);

  RETURN v_id;
END;
$$;


-- ========== FUNCTION: approve_reservation (BR-B4-04, BR-B4-06) ==========
CREATE OR REPLACE FUNCTION public.approve_reservation(p_reservation_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- BR-B4-04: Only Administrator may approve
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'administrator'
  ) THEN
    RAISE EXCEPTION 'BR-B4-04: Only administrators can approve reservations.';
  END IF;

  -- Only Pending can be approved
  IF NOT EXISTS (
    SELECT 1 FROM public.reservations WHERE id = p_reservation_id AND status = 'Pending'
  ) THEN
    RAISE EXCEPTION 'Only pending reservations can be approved.';
  END IF;

  -- BR-B4-03: Re-check for conflicts at approval time
  IF EXISTS (
    SELECT 1 FROM public.reservations r2
    JOIN public.reservations r1 ON r1.id = p_reservation_id
    WHERE r2.facility_id = r1.facility_id
      AND r2.id <> p_reservation_id
      AND r2.status IN ('Approved', 'Scheduled', 'In Use')
      AND r1.start_datetime < r2.end_datetime
      AND r1.end_datetime > r2.start_datetime
  ) THEN
    RAISE EXCEPTION 'BR-B4-03: Approving would create an overlapping schedule.';
  END IF;

  -- BR-B4-06: Approved → Scheduled (reserves the time slot)
  UPDATE public.reservations
     SET status = 'Scheduled', approved_by = auth.uid(), approved_at = NOW()
   WHERE id = p_reservation_id;

  -- BR-B4-10: Audit
  PERFORM public.log_audit('APPROVE', 'reservations', p_reservation_id,
    'Reservation approved and scheduled.');
END;
$$;


-- ========== FUNCTION: reject_reservation (BR-B4-04) ==========
CREATE OR REPLACE FUNCTION public.reject_reservation(p_reservation_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- BR-B4-04: Only Administrator may reject
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'administrator'
  ) THEN
    RAISE EXCEPTION 'BR-B4-04: Only administrators can reject reservations.';
  END IF;

  -- Only Pending can be rejected
  IF NOT EXISTS (
    SELECT 1 FROM public.reservations WHERE id = p_reservation_id AND status = 'Pending'
  ) THEN
    RAISE EXCEPTION 'Only pending reservations can be rejected.';
  END IF;

  UPDATE public.reservations SET status = 'Rejected' WHERE id = p_reservation_id;

  -- BR-B4-10: Audit
  PERFORM public.log_audit('REJECT', 'reservations', p_reservation_id,
    'Reservation rejected.');
END;
$$;


-- ========== FUNCTION: cancel_reservation (BR-B4-09) ==========
CREATE OR REPLACE FUNCTION public.cancel_reservation(p_reservation_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_user UUID; v_status TEXT;
BEGIN
  SELECT user_id, status INTO v_user, v_status
  FROM public.reservations WHERE id = p_reservation_id;

  -- BR-B4-09: Requesters may modify only their own Pending requests
  IF v_user <> auth.uid() THEN
    RAISE EXCEPTION 'BR-B4-09: You can only cancel your own reservations.';
  END IF;

  IF v_status <> 'Pending' THEN
    RAISE EXCEPTION 'BR-B4-09: Only pending reservations can be cancelled.';
  END IF;

  UPDATE public.reservations SET status = 'Cancelled' WHERE id = p_reservation_id;

  -- BR-B4-10: Audit
  PERFORM public.log_audit('CANCEL', 'reservations', p_reservation_id,
    'Reservation cancelled by requester.');
END;
$$;


-- ========== FUNCTION: mark_in_use (Staff) ==========
CREATE OR REPLACE FUNCTION public.mark_in_use(p_reservation_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Only staff or admin
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('facility_staff', 'administrator')
  ) THEN
    RAISE EXCEPTION 'Only facility staff can confirm usage.';
  END IF;

  -- Only Scheduled can move to In Use
  IF NOT EXISTS (
    SELECT 1 FROM public.reservations WHERE id = p_reservation_id AND status = 'Scheduled'
  ) THEN
    RAISE EXCEPTION 'Only scheduled reservations can be marked In Use.';
  END IF;

  UPDATE public.reservations SET status = 'In Use' WHERE id = p_reservation_id;

  -- BR-B4-10: Audit
  PERFORM public.log_audit('STATUS_CHANGE', 'reservations', p_reservation_id,
    'Reservation marked as In Use.');
END;
$$;


-- ========== FUNCTION: complete_reservation (Staff, BR-B4-07) ==========
CREATE OR REPLACE FUNCTION public.complete_reservation(p_reservation_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Only staff or admin
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('facility_staff', 'administrator')
  ) THEN
    RAISE EXCEPTION 'Only facility staff can complete reservations.';
  END IF;

  -- Only In Use can be completed
  IF NOT EXISTS (
    SELECT 1 FROM public.reservations WHERE id = p_reservation_id AND status = 'In Use'
  ) THEN
    RAISE EXCEPTION 'Only In Use reservations can be completed.';
  END IF;

  UPDATE public.reservations SET status = 'Completed' WHERE id = p_reservation_id;

  -- BR-B4-10: Audit
  PERFORM public.log_audit('COMPLETE', 'reservations', p_reservation_id,
    'Reservation completed.');
END;
$$;


-- ========== FUNCTION: log_facility_change ==========
CREATE OR REPLACE FUNCTION public.log_facility_change(
  p_facility_id BIGINT,
  p_action TEXT,
  p_details TEXT DEFAULT ''
) RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.log_audit(p_action, 'facilities', p_facility_id, p_details);
END;
$$;


-- ========== GRANT EXECUTE ==========
GRANT EXECUTE ON FUNCTION public.log_audit(TEXT, TEXT, BIGINT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_reservation(BIGINT, TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_reservation(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reject_reservation(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_reservation(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_in_use(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_reservation(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_facility_change(BIGINT, TEXT, TEXT) TO authenticated;
